/**
 * Issue Planning Agent
 *
 * Triggered by GitHub Actions when an issue is labeled "ready-for-planning".
 * Reads the issue title + body, explores the codebase, and posts a structured
 * implementation plan as a comment on the issue.
 */

import { Agent, CursorAgentError } from "@cursor/sdk";
import { execSync } from "child_process";
import { readFileSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, "..");

const issueNumber = process.env.ISSUE_NUMBER;
const issueTitle = process.env.ISSUE_TITLE;
const repo = process.env.GITHUB_REPOSITORY;

if (!issueNumber || !issueTitle || !repo) {
  console.error("Missing required env vars: ISSUE_NUMBER, ISSUE_TITLE, GITHUB_REPOSITORY");
  process.exit(1);
}

if (!process.env.CURSOR_API_KEY) {
  console.error("Missing CURSOR_API_KEY");
  process.exit(1);
}

// Read project standards
let agentsMd = "";
try {
  agentsMd = readFileSync(join(repoRoot, "AGENTS.md"), "utf8");
} catch {
  agentsMd = "(AGENTS.md not found)";
}

const MAX_ISSUE_BODY_CHARS = 4_000;
const MAX_SOURCE_CHARS = 6_000;
const MAX_TREE_CHARS = 3_000;

function truncate(str, max, label) {
  if (str.length <= max) return str;
  return str.slice(0, max) + `\n... (${label} truncated at ${max} chars)`;
}

// Snapshot the current project structure for context
let projectTree = "";
try {
  const raw = execSync("find lib test -type f -name '*.dart' | sort", {
    cwd: repoRoot,
    maxBuffer: 512 * 1024,
  }).toString();
  projectTree = truncate(raw, MAX_TREE_CHARS, "file tree");
} catch {
  projectTree = "(could not list project files)";
}

// Read key architecture files so the agent understands current wiring
function tryRead(relPath) {
  try {
    return readFileSync(join(repoRoot, relPath), "utf8");
  } catch {
    return `(${relPath} not found)`;
  }
}

const issueBody = truncate(process.env.ISSUE_BODY ?? "", MAX_ISSUE_BODY_CHARS, "issue body");

const routerSource = truncate(tryRead("lib/app/router/app_router.dart"), MAX_SOURCE_CHARS, "router");
const diSource = truncate(tryRead("lib/app/di/service_locator.dart"), MAX_SOURCE_CHARS, "service_locator");
const pubspec = truncate(tryRead("pubspec.yaml"), MAX_SOURCE_CHARS, "pubspec");

const prompt = `
You are a senior Flutter/Dart engineer on the pulse_coaching_app project.
A new GitHub issue has been labeled "ready-for-planning". Your job is to produce
a thorough implementation plan that a developer (human or AI) can follow without
ambiguity.

## Project standards (AGENTS.md)
${agentsMd}

## Current dependencies (pubspec.yaml)
${pubspec}

## Current routing (app_router.dart)
${routerSource}

## Current DI setup (service_locator.dart)
${diSource}

## All Dart files currently in the project
${projectTree}

---

## Issue to plan

**Title:** ${issueTitle}

**Body:**
${issueBody || "(no description provided)"}

---

## Your task

Produce a structured implementation plan with the following sections.
Be specific — name actual files, classes, and methods. Do not be vague.

### 1. Summary
One paragraph describing what this change does and why.

### 2. Files to create
List each new file with its path and one-sentence purpose.

### 3. Files to modify
List each existing file with the specific change required.

### 4. Architecture impact
Does this change the feature structure, DI graph, routing, or data flow? Explain.

### 5. State management
Which pattern applies (BLoC / MVVM / ChangeNotifier)? Why? Which classes are involved?

### 6. Test plan
List specific test cases: what to test, which file, which pattern (unit / widget / integration).

### 7. Risks and edge cases
What could go wrong? What assumptions are being made?

### 8. Questions / assumptions
Anything that needs clarification before coding starts?

Keep each section concise and actionable. Do not write any code — this is a plan only.
`.trim();

console.log(`Running planning agent for issue #${issueNumber}: "${issueTitle}"...`);

let planText;
try {
  const result = await Agent.prompt(prompt, {
    apiKey: process.env.CURSOR_API_KEY,
    model: { id: "composer-2.5" },
    local: { cwd: repoRoot },
  });

  if (result.status !== "finished") {
    console.error(`Agent finished with status: ${result.status}`);
    process.exit(2);
  }

  planText = result.result ?? "(no output)";
} catch (err) {
  if (err instanceof CursorAgentError) {
    console.error(`Agent startup failed: ${err.message} (retryable=${err.isRetryable})`);
    process.exit(1);
  }
  throw err;
}

const body = `## Implementation Plan

${planText}

---
*Generated by [Cursor Planning Agent](https://cursor.com) · [View run logs](https://github.com/${repo}/actions)*
*Review the plan above, then open Cursor and say: "implement issue #${issueNumber}".*`;

const bodyFile = "/tmp/issue_plan_body.md";
writeFileSync(bodyFile, body, "utf8");

try {
  execSync(
    `gh issue comment ${issueNumber} --repo ${repo} --body-file ${bodyFile}`,
    { stdio: "inherit" }
  );
  console.log(`Plan posted to issue #${issueNumber}.`);
} catch {
  console.error("Failed to post issue comment. Check GH_TOKEN permissions.");
  process.exit(1);
}
